[[plugins]]
repo = 'Shougo/dein.vim'

[[plugins]]
repo = 'sheerun/vim-polyglot'

[[plugins]]
repo = 'arzg/vim-colors-xcode'
hook_add = """
  let g:signify_sign_show_count = 0

  if !exists('g:color_scheme')
    let g:color_scheme = 'xcodelighthc'
  endif
  try
    execute 'colorscheme '.g:color_scheme
  catch
  endtry
"""
